sudo: false
language: python
env:
    global:
        - COVERAGE=1 RUNTEST_ARGS=-v
    matrix:
        # Quality checks
        - TOXENV=flake8
        - TOXENV=docs
        # Supported Python / Django versions
        - TOXENV=py27-django-18
        - TOXENV=py34-django-18
        - TOXENV=py27-django-17
        - TOXENV=py34-django-17
        - TOXENV=py26-django-14
        - TOXENV=py27-django-14
        # Django master is allowed to fail
        - TOXENV=py27-django-master
        - TOXENV=py34-django-master
matrix:
    allow_failures:
        - env: TOXENV=py27-django-master
        - env: TOXENV=py34-django-master
install: pip install tox coveralls
before_script: coverage erase
script: tox
after_success: coveralls
