sudo: false
language: python
env:
    global:
        - COVERAGE=1 RUNTEST_ARGS=-v
    matrix:
        # Most important builds
        - TOXENV=flake8
        - TOXENV=py27-django-18
        - TOXENV=py34-django-18
        - TOXENV=py27-django-17
        - TOXENV=py34-django-17
        - TOXENV=py27-django-16
        - TOXENV=py32-django-16
        - TOXENV=py26-django-14
        # Redundant builds that might be dropped
        - TOXENV=py32-django-18
        - TOXENV=py33-django-18
        - TOXENV=py32-django-17
        - TOXENV=py33-django-17
        - TOXENV=py26-django-16
        - TOXENV=py33-django-16
        - TOXENV=py34-django-16
        # Django master builds that are allowed to fail
        - TOXENV=py27-django-master
        - TOXENV=py34-django-master
matrix:
    allow_failures:
        - env: TOXENV=py27-django-master
        - env: TOXENV=py34-django-master
install: pip install tox coveralls
before_script: coverage erase
script: tox
after_success: coveralls
