sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - REQUIREMENTS=django-14
  - REQUIREMENTS=django-16
  - REQUIREMENTS=django-17
  - REQUIREMENTS=django-18
  - REQUIREMENTS=django-master

matrix:
  allow_failures:
    - env: REQUIREMENTS=django-master
  exclude:
    - python: "3.2"
      env: REQUIREMENTS=django-14
    - python: "3.3"
      env: REQUIREMENTS=django-14
    - python: "3.4"
      env: REQUIREMENTS=django-14
    - python: "2.6"
      env: REQUIREMENTS=django-17
    - python: "2.6"
      env: REQUIREMENTS=django-18
    - python: "2.6"
      env: REQUIREMENTS=django-master

install:
  - pip install tox

script:
  - tox -e py-$REQUIREMENTS
